export const ERRORS = {
  WRONG_COMBO: "Wrong username/email or password!",
  NO_SPACES_USER: "You cannot have a space in your username/email!",
  NO_SPACES_PASS: "You cannot have a space in your password!",
  NAME_REQ: "Name required!",
  USERNAME_REQ: "Username required!",
  USERNAME_INVALID:
    "Username must be between 3-16 characters long and cannot contain special characters!",
  EMAIL_REQ: "Email required!",
  EMAIL_INVALID: "Email is invalid!",
  PASSWORD_REQ: "Password required!",
  PASSWORD_INVALID:
    "Password must be 6-18 characters long with at least 1 letter and 1 number!",
  PASSWORD_NOTMATCH: "Passwords are not the same!",
  UID_REQ: "UID required!",
  UID_INVALID: "UID must be 9 numbers long!",
  PRODUCT_NAME_REQ: "Product name required!",
  PRICE_REQ: "Price required!",
  PRICE_INVALID: "Price invalid!",
  STOCK_REQ: "Stock required!",
  STOCK_INVALID: "Stock invalid!",
  SHORT_DESC_REQ: "You must input a short description for your product!",
  DESC_REQ: "You must input a longer description for your product as well!",
  CONDITION_REQ: "You must input what condition your product is in!",
};
